### ISSUE TITLE
http://localhost:4200/ shows a blank page

### ISSUE THREAD

**Issue by frank3manuel** [rjaviervega/ember-xmpp-im#1]
It worked once before, but when I tried changing my settings, node version and ember version, it stopped working and started showing blank. I returned all settings to their original state, even pulling a fresh copy of the project, and now I'm getting a blank screen every time.

This is the result of "ember server":

version: 0.1.2
Livereload server on port 35729
Serving on http://0.0.0.0:4200/

Build successful - 956ms.

Slowest Trees                  | Total  
-------------------------------+----------------
ES3SafeFilter                  | 316ms  
JSHint - App                   | 160ms  
ES6Concatenator                | 146ms  
Concat                         | 60ms  
JSHint - Tests                 | 52ms  
TemplateCompiler               | 52ms           

And this is "ember -v"
version: 0.1.2
node: 0.12.7
npm: 2.1.3

They are both the same output as when it ran successfully, but now I get a blank screen (on Chrome and Firefox).

What am I doing wrong, and what should I be looking at?

Thanks,
Frank

**Comment by rjaviervega** [comment]
Check what version of Jquery your installation is using. Try setting to fixed version 1.11.3 on bower.json. I think ember-cli breaks with the latest jquery. Please confirm if this fixes your issue.
{
  "dependencies": {
    "jquery": "1.11.3",
  }
}

**Comment by frank3manuel** [comment]
Thanks, I'll try this, but I've encountered another error after upgrading my node. (I'll post another ticket for that). 

I'll revisit this ticket when done. Thanks a bunch.

**Comment by frank3manuel** [comment]
This is confirmed resolved. Thanks very much.
